#!/bin/bash

BASE=$(git config core.worktree)
NEW_MODULES="$BASE/.gitmodules.d/$VCSH_REPO_NAME"
MODULES="$BASE/.gitmodules"

[ -d .gitmodules.d ] || mkdir .gitmodules.d

if git ls-files --error-unmatch "$MODULES" >/dev/null 2>&1; then
	git mv -f "$MODULES" "$NEW_MODULES"
fi
