#!/bin/bash

if [ -n "$GIT_DIR" -a -n "$VCSH_REPO_NAME" ]; then
	BASE=$(git config core.worktree)
	[ -z "$BASE" ] && exit 0
	MODULES="$BASE/.gitmodules"
	if [ -L "$MODULES" ]; then
		LINK=$(readlink "$MODULES")
		TGT="$BASE/.gitmodules.d/$VCSH_REPO_NAME"
		if [ "x$LINK" == "x$TGT" ]; then
			if git ls-files --error-unmatch "$MODULES" >/dev/null 2>&1; then
				git rm "$MODULES"
			else
				rm "$MODULES"
			fi
		fi
	fi
fi
