#!/bin/bash

case "$VCSH_COMMAND" in
	run);;
	enter);;
	*) exit 0;;
esac

if [ -n "$GIT_DIR" -a -n "$VCSH_REPO_NAME" ]; then
	BASE=$(git config core.worktree)
	[ -z "$BASE" ] && exit 0
	[ -e "$BASE/.gitmodules" ] || \
		ln -s "$BASE/.gitmodules.d/$VCSH_REPO_NAME" "$BASE/.gitmodules"
fi
