#!/bin/bash

[ -d .gitmodules.d ] || mkdir .gitmodules.d

GITMODULES=".gitmodules.d/$VCSH_REPO_NAME"
[ ! -f "$GITMODULES" -a -f ".gitmodules" ] && GITMODULES=".gitmodules"

[[ "$GITMODULES" != ".gitmodules" ]] && ln -s "$GITMODULES" .gitmodules

"$GIT_EXEC_PATH_ORIG/git-submodule" "$@"

[[ "$GITMODULES" != ".gitmodules" ]] && rm .gitmodules
