#!/bin/bash

: ${XDG_CONFIG_HOME:="$HOME/.config"}

EXEC_PATH="$(git --exec-path)"
export GIT_EXEC_PATH_ORIG="${EXEC_PATH##*:}"
NEWPATH="$XDG_CONFIG_HOME/vcsh/gitmodules"
case "$EXEC_PATH" in
	*"${NEWPATH}:"*);;
	*) export GIT_EXEC_PATH="$NEWPATH:$EXEC_PATH";;
esac
